Organized README
ibnesayeed/linkextractor pull request #5
Opened 2019-02-20 23:18 UTC by avinashdesireddy

Play-with-docker reference is added and organized the references.

2019-02-20 23:20 UTC, avinashdesireddy commented
#2

2019-02-20 23:47 UTC, ibnesayeed requested changes
Thanks for this PR. Please accept my suggestions or make them yourself in a follow up commit to the PR.

2019-02-20 23:47 UTC, ibnesayeed commented on README.md
> +Link Extractor app scrapes links from a given web page. This repository illistrates step by step approach to learn [Docker](https://www.docker.com/).
Split sentences in separate lines (not mandatory, but is the undocumented chosen style in this repo). Also, fixing a typo.

```md
Link Extractor app scrapes links from a given web page.
This repository illustrates step by step approach to learn [Docker](https://www.docker.com/).
```

2019-02-20 23:47 UTC, ibnesayeed commented on README.md
> +## How to Use the repository
Correct letter cases in the heading and add a blank line after it.

```md
## How to Use the Repository

```

2019-02-20 23:47 UTC, ibnesayeed commented on README.md
> +2. Follow instructions in the `README` files of various folders from `step0` to `step6` and explore corresponding code.
The two options are mutually exclusive, so I would start the second point a little differently.

```md
2. Alternatively, if running on a local Docker installation, follow instructions in the `README` files of various folders from `step0` to `step6` and explore corresponding code.
```

2019-02-20 23:47 UTC, ibnesayeed commented on README.md
> +1. [Play with Docker Classroom](https://training.play-with-docker.com/microservice-orchestration/) helps to start your docker journey without any additional overhead of configuring docker locally.
Proper casing of Docker as a proper noun.

```md
1. [Play with Docker Classroom](https://training.play-with-docker.com/microservice-orchestration/) helps to start your Docker exploration journey without any additional overhead of installing and configuring Docker locally.
```

2019-02-20 23:47 UTC, ibnesayeed commented on README.md
> +## References
A blank line after the heading.

```md
## References

```

2019-02-20 23:53 UTC, ibnesayeed commented
Read about incorporating suggested changes at https://help.github.com/articles/incorporating-feedback-in-your-pull-request/

2019-02-21 15:41 UTC, avinashdesireddy commented
@ibnesayeed applied the suggestions. Please review and merge the PR.

2019-02-21 15:41 UTC, ibnesayeed approved these changes

2019-02-21 15:42 UTC, ibnesayeed commented
LGTM! Thanks @avinashdesireddy for the PR.

2019-02-21 15:43 UTC, merged